version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672   # Cổng AMQP
      - 15672:15672 # Cổng giao diện quản lý web
    environment:
      RABBITMQ_DEFAULT_USER: codecamp
      RABBITMQ_DEFAULT_PASS: 123@123abc
    volumes:
      - ./data:/bitnami/rabbitmq